/* eslint-disable no-sparse-arrays */
import { Colors } from "./types";

export const trophy = [
	[, , , ...new Array(11).fill(Colors.BgBlack)],
	[
		,
		,
		,
		Colors.BgBlack,
		...new Array(8).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
	],
	[
		...new Array(4).fill(Colors.BgBlack),
		Colors.BgYellow,
		Colors.BgWhite,
		...new Array(6).fill(Colors.BgYellow),
		Colors.BgRed,
		...new Array(4).fill(Colors.BgBlack),
	],
	[
		Colors.BgBlack,
		,
		,
		Colors.BgBlack,
		Colors.BgYellow,
		Colors.BgWhite,
		...new Array(6).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
		,
		,
		Colors.BgBlack,
	],
	[
		Colors.BgBlack,
		,
		,
		Colors.BgBlack,
		Colors.BgYellow,
		Colors.BgWhite,
		...new Array(6).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
		,
		,
		Colors.BgBlack,
	],
	[
		Colors.BgBlack,
		Colors.BgBlack,
		,
		Colors.BgBlack,
		Colors.BgYellow,
		Colors.BgWhite,
		...new Array(6).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
		,
		Colors.BgBlack,
		Colors.BgBlack,
	],
	[
		,
		Colors.BgBlack,
		Colors.BgBlack,
		Colors.BgBlack,
		Colors.BgYellow,
		Colors.BgWhite,
		...new Array(6).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
		Colors.BgBlack,
		Colors.BgBlack,
	],
	[
		,
		,
		,
		Colors.BgBlack,
		Colors.BgBlack,
		...new Array(6).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
		Colors.BgBlack,
	],
	[
		,
		,
		,
		,
		Colors.BgBlack,
		Colors.BgBlack,
		...new Array(4).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
		Colors.BgBlack,
	],
	[
		,
		,
		,
		,
		,
		Colors.BgBlack,
		Colors.BgBlack,
		Colors.BgYellow,
		Colors.BgYellow,
		Colors.BgRed,
		Colors.BgBlack,
		Colors.BgBlack,
	],
	[, , , , , , , Colors.BgBlack, Colors.BgYellow, Colors.BgBlack],
	[, , , , , , , Colors.BgBlack, Colors.BgYellow, Colors.BgBlack],
	[, , , , , , , Colors.BgBlack, Colors.BgYellow, Colors.BgBlack],
	[
		,
		,
		,
		,
		,
		,
		Colors.BgBlack,
		Colors.BgBlack,
		Colors.BgYellow,
		Colors.BgBlack,
		Colors.BgBlack,
	],
	[
		,
		,
		,
		,
		,
		Colors.BgBlack,
		...new Array(4).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
	],
	[, , , , , ...new Array(7).fill(Colors.BgBlack)],
];
export const trophyColumns = 17;
