/* eslint-disable no-sparse-arrays */
import type { PixelArt } from "./types";
import { Colors } from "./types";

/**
 * Pixel arts are 2d arrays of colors.
 * Every pixel art also exports the number of columns as it's not easy to retrieve it from the array.
 */

/** */
export const trophy: PixelArt = [
	[, , , ...new Array(11).fill(Colors.BgBlack)],
	[
		,
		,
		,
		Colors.BgBlack,
		...new Array(8).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
	],
	[
		...new Array(4).fill(Colors.BgBlack),
		Colors.BgYellow,
		Colors.BgWhite,
		...new Array(6).fill(Colors.BgYellow),
		Colors.BgRed,
		...new Array(4).fill(Colors.BgBlack),
	],
	[
		Colors.BgBlack,
		,
		,
		Colors.BgBlack,
		Colors.BgYellow,
		Colors.BgWhite,
		...new Array(6).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
		,
		,
		Colors.BgBlack,
	],
	[
		Colors.BgBlack,
		,
		,
		Colors.BgBlack,
		Colors.BgYellow,
		Colors.BgWhite,
		...new Array(6).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
		,
		,
		Colors.BgBlack,
	],
	[
		Colors.BgBlack,
		Colors.BgBlack,
		,
		Colors.BgBlack,
		Colors.BgYellow,
		Colors.BgWhite,
		...new Array(6).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
		,
		Colors.BgBlack,
		Colors.BgBlack,
	],
	[
		,
		Colors.BgBlack,
		Colors.BgBlack,
		Colors.BgBlack,
		Colors.BgYellow,
		Colors.BgWhite,
		...new Array(6).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
		Colors.BgBlack,
		Colors.BgBlack,
	],
	[
		,
		,
		,
		Colors.BgBlack,
		Colors.BgBlack,
		...new Array(6).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
		Colors.BgBlack,
	],
	[
		,
		,
		,
		,
		Colors.BgBlack,
		Colors.BgBlack,
		...new Array(4).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
		Colors.BgBlack,
	],
	[
		,
		,
		,
		,
		,
		Colors.BgBlack,
		Colors.BgBlack,
		Colors.BgYellow,
		Colors.BgYellow,
		Colors.BgRed,
		Colors.BgBlack,
		Colors.BgBlack,
	],
	[, , , , , , , Colors.BgBlack, Colors.BgYellow, Colors.BgBlack],
	[, , , , , , , Colors.BgBlack, Colors.BgYellow, Colors.BgBlack],
	[, , , , , , , Colors.BgBlack, Colors.BgYellow, Colors.BgBlack],
	[
		,
		,
		,
		,
		,
		,
		Colors.BgBlack,
		Colors.BgBlack,
		Colors.BgYellow,
		Colors.BgBlack,
		Colors.BgBlack,
	],
	[
		,
		,
		,
		,
		,
		Colors.BgBlack,
		...new Array(4).fill(Colors.BgYellow),
		Colors.BgRed,
		Colors.BgBlack,
	],
	[, , , , , ...new Array(7).fill(Colors.BgBlack)],
];
export const trophyColumns = 17;
